<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Platform.Application/Platform.Application.csproj" />
    <ProjectReference Include="../Platform.Infrastructure/Platform.Infrastructure.csproj" />
  </ItemGroup>
</Project>
